### ISSUE TITLE
Lighthouse / PageSpeed Insights

### ISSUE THREAD

**Issue by benmccann** [shuding/cobe#38]
Hi, I'm working on a [new homepage for SvelteKit](https://github.com/sveltejs/kit/pull/5869) and one idea we're considering is adding a WebGL globe - possibly with COBE. We try to keep our PageSpeed score high since developers who are considering us sometimes use our site as an example of how performant Svelte is ([example](https://www.speedlify.dev/ssg/)). We consistently score in the 90s. However, the COBE site scored only 47 for me. I'm not sure if this is because of COBE itself or some other aspect of the site. It'd be great if the COBE site scored high so that I could have confidence that using COBE would not affect our own page's speed.

https://pagespeed.web.dev/report?url=https%3A%2F%2Fcobe.vercel.app%2F&form_factor=mobile

**Comment by shuding** [comment]
This is definitely critical and it's what COBE was made for. I think COBE should be way more performant than most of WebGL solutions out there. It's strange to have only 47, because it scored 100 for me:

<img width="1679" alt="CleanShot 2022-08-18 at 16 44 40@2x" src="https://user-images.githubusercontent.com/3676859/185424052-a7dc81d0-49c6-49b0-8e04-d3498e2cb3c1.png">

**Comment by benmccann** [comment]
It's very bizarre that Chrome DevTools and PageSpeed Insights are giving such different results for this. I've filed an issue in the Lighthouse repository: https://github.com/GoogleChrome/lighthouse/issues/14301. Hopefully they can shed some light on it.

**Comment by shuding** [comment]
Btw let me know if there's anything I can help, if you decide to go with this library :)

**Comment by benmccann** [comment]
They said it's because the web-based PageSpeed Insights tool just runs WebGL with software rendering and there's a ticket to track that: https://github.com/GoogleChrome/lighthouse/issues/8557

I wonder if there's a way to detect if hardware rendering is enabled and only display the animation on https://cobe.vercel.app/ if it is?

**Comment by shuding** [comment]
This means every WebGL page will have the issue with PageSpeed Insights then. Personally I don’t think it makes sense to  hack it to bypass performance measurement tools (because it can’t represent the real world usage then). But yeah you can for sure render a static image instead of this component if hardware rendering isn’t supported.

**Comment by benmccann** [comment]
I guess the question is what will you want to show to a real user if they don't have hardware acceleration. I agree we shouldn't special case performance measurement tools. I'm not sure what the experience on a non-accelerated machine would be generally though and whether it still makes sense to show the animation in that case

**Comment by shuding** [comment]
Yep! In our product we show a video of that same rotating globe if WebGL isn't supported, I think it works great in this case too.

**Comment by benmccann** [comment]
Cool. Thanks for the help!
